name: Graphs CI
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  graphs:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1
        with:
          command: "graphs"
