name: Response Time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
jobs:
  response-time:
    name: Check response time
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1
        with:
          command: "response-time"
