name: Response-time CI
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pages: write

jobs:
  response-time:
    name: Check response time
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
