name: Site CI
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pages: write

jobs:
  site:
    name: Run site
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
