name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  issues: write
  pages: write
  id-token: write

jobs:
  uptime:
    name: Uptime monitoring
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "readme"
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "site"
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "graphs"
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "response-time"
      - uses: upptime/uptime-monitor@v1.41.0
        with:
          command: "summary"
