name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  uptime:
    name: Uptime monitoring
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@v1
        with:
          command: "readme"
      - uses: upptime/uptime-monitor@v1
        with:
          command: "site"
      - uses: upptime/uptime-monitor@v1
        with:
          command: "graphs"
      - uses: upptime/uptime-monitor@v1
        with:
          command: "response-time"
      - uses: upptime/uptime-monitor@v1
        with:
          command: "summary"
